### ISSUE TITLE
issue with requirements

### ISSUE THREAD

**Issue by brad-taylor-yvr** [devLotto/teleport#4]
I have pulled python3 from python.org and pip via `curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`

When I run `pip install -r requirements.txt` I get this:
  
```
Collecting aiortc==1.2.0
  Using cached aiortc-1.2.0.tar.gz (1.2 MB)
  Preparing metadata (setup.py) ... done
Collecting requests==2.25.1
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting cryptography<39
  Using cached cryptography-38.0.4-cp36-abi3-macosx_10_10_universal2.whl (5.4 MB)
Collecting aioice<0.8.0,>=0.7.5
  Using cached aioice-0.7.6-py3-none-any.whl (23 kB)
Collecting av<9.0.0,>=8.0.0
  Using cached av-8.1.0.tar.gz (2.4 MB)
  Preparing metadata (setup.py) ... done
Collecting cffi>=1.0.0
  Using cached cffi-1.15.1-cp311-cp311-macosx_11_0_arm64.whl (174 kB)
Requirement already satisfied: crc32c>=2.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aiortc==1.2.0->-r requirements.txt (line 1)) (2.3.post0)
Collecting pyee>=6.0.0
  Using cached pyee-9.0.4-py2.py3-none-any.whl (14 kB)
Collecting pylibsrtp>=0.5.6
  Using cached pylibsrtp-0.8.0-cp311-cp311-macosx_11_0_arm64.whl (52 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests==2.25.1->-r requirements.txt (line 2)) (2022.12.7)
Collecting dnspython>=2.0.0
  Using cached dnspython-2.3.0-py3-none-any.whl (283 kB)
Requirement already satisfied: netifaces in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from aioice<0.8.0,>=0.7.5->aiortc==1.2.0->-r requirements.txt (line 1)) (0.11.0)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Building wheels for collected packages: aiortc, av
  Building wheel for aiortc (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/ml/88rl8rbx11g__x77rx7nll_00000gn/T/pip-install-72d47f56/aiortc_a16a9401454444258cce8fad413895f2/setup.py", line 44, in <module>
          setuptools.setup(
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
                                 ^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/wheel.py", line 110, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/wheel.py", line 118, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/wheel.py", line 162, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/ml/88rl8rbx11g__x77rx7nll_00000gn/T/pip-install-72d47f56/aiortc_a16a9401454444258cce8fad413895f2/.eggs/cffi-1.15.1-py3.11-macosx-10.9-universal2.egg/cffi-1.15.1.dist-info' -> '/private/var/folders/ml/88rl8rbx11g__x77rx7nll_00000gn/T/pip-install-72d47f56/aiortc_a16a9401454444258cce8fad413895f2/.eggs/cffi-1.15.1-py3.11-macosx-10.9-universal2.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for aiortc
  Running setup.py clean for aiortc
  error: subprocess-exited-with-error
  
  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [35 lines of output]
      /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
        warnings.warn(
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/ml/88rl8rbx11g__x77rx7nll_00000gn/T/pip-install-72d47f56/aiortc_a16a9401454444258cce8fad413895f2/setup.py", line 44, in <module>
          setuptools.setup(
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 86, in setup
          _install_setup_requires(attrs)
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/dist.py", line 875, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pkg_resources/__init__.py", line 789, in resolve
          dist = best[req.key] = env.best_match(
                                 ^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1075, in best_match
          return self.obtain(req, installer)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pkg_resources/__init__.py", line 1087, in obtain
          return installer(requirement)
                 ^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/dist.py", line 945, in fetch_build_egg
          return fetch_build_egg(self, req)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/installer.py", line 87, in fetch_build_egg
          wheel.install_as_egg(dist_location)
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/wheel.py", line 110, in install_as_egg
          self._install_as_egg(destination_eggdir, zf)
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/wheel.py", line 118, in _install_as_egg
          self._convert_metadata(zf, destination_eggdir, dist_info, egg_info)
        File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/wheel.py", line 162, in _convert_metadata
          os.rename(dist_info, egg_info)
      OSError: [Errno 66] Directory not empty: '/private/var/folders/ml/88rl8rbx11g__x77rx7nll_00000gn/T/pip-install-72d47f56/aiortc_a16a9401454444258cce8fad413895f2/.eggs/cffi-1.15.1-py3.11-macosx-10.9-universal2.egg/cffi-1.15.1.dist-info' -> '/private/var/folders/ml/88rl8rbx11g__x77rx7nll_00000gn/T/pip-install-72d47f56/aiortc_a16a9401454444258cce8fad413895f2/.eggs/cffi-1.15.1-py3.11-macosx-10.9-universal2.egg/EGG-INFO'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for aiortc
  Building wheel for av (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-311
      creating build/lib.macosx-10.9-universal2-cpython-311/av
      copying av/deprecation.py -> build/lib.macosx-10.9-universal2-cpython-311/av
      copying av/datasets.py -> build/lib.macosx-10.9-universal2-cpython-311/av
      copying av/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/av
      copying av/__main__.py -> build/lib.macosx-10.9-universal2-cpython-311/av
      creating build/lib.macosx-10.9-universal2-cpython-311/av/video
      copying av/video/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/av/video
      creating build/lib.macosx-10.9-universal2-cpython-311/av/codec
      copying av/codec/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/av/codec
      creating build/lib.macosx-10.9-universal2-cpython-311/av/container
      copying av/container/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/av/container
      creating build/lib.macosx-10.9-universal2-cpython-311/av/audio
      copying av/audio/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/av/audio
      creating build/lib.macosx-10.9-universal2-cpython-311/av/subtitles
      copying av/subtitles/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/av/subtitles
      creating build/lib.macosx-10.9-universal2-cpython-311/av/filter
      copying av/filter/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/av/filter
      creating build/lib.macosx-10.9-universal2-cpython-311/av/sidedata
      copying av/sidedata/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/av/sidedata
      creating build/lib.macosx-10.9-universal2-cpython-311/av/data
      copying av/data/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/av/data
      running build_ext
      running config
      pkg-config is required for building PyAV
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for av
  Running setup.py clean for av
Failed to build aiortc av
Installing collected packages: av, urllib3, typing-extensions, pycparser, idna, dnspython, chardet, requests, pyee, cffi, aioice, pylibsrtp, cryptography, aiortc
  Running setup.py install for av ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for av did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      running install
      /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-311
      creating build/lib.macosx-10.9-universal2-cpython-311/av
      copying av/deprecation.py -> build/lib.macosx-10.9-universal2-cpython-311/av
      copying av/datasets.py -> build/lib.macosx-10.9-universal2-cpython-311/av
      copying av/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/av
      copying av/__main__.py -> build/lib.macosx-10.9-universal2-cpython-311/av
      creating build/lib.macosx-10.9-universal2-cpython-311/av/video
      copying av/video/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/av/video
      creating build/lib.macosx-10.9-universal2-cpython-311/av/codec
      copying av/codec/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/av/codec
      creating build/lib.macosx-10.9-universal2-cpython-311/av/container
      copying av/container/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/av/container
      creating build/lib.macosx-10.9-universal2-cpython-311/av/audio
      copying av/audio/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/av/audio
      creating build/lib.macosx-10.9-universal2-cpython-311/av/subtitles
      copying av/subtitles/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/av/subtitles
      creating build/lib.macosx-10.9-universal2-cpython-311/av/filter
      copying av/filter/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/av/filter
      creating build/lib.macosx-10.9-universal2-cpython-311/av/sidedata
      copying av/sidedata/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/av/sidedata
      creating build/lib.macosx-10.9-universal2-cpython-311/av/data
      copying av/data/__init__.py -> build/lib.macosx-10.9-universal2-cpython-311/av/data
      running build_ext
      running config
      pkg-config is required for building PyAV
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> av

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

python newbie here... any quick fixes?

thanks... :)

**Comment by alexanderhenne** [comment]
I have merged https://github.com/alexanderhenne/teleport/pull/2, could you try now?

**Comment by brad-taylor-yvr** [comment]
Getting the requirements installed looks pretty clean to me now...

```
pip install -r requirements.txt 
Collecting aiortc-datachannel-only==1.3.2.post3
  Downloading aiortc_datachannel_only-1.3.2.post3-py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.3/90.3 kB 2.1 MB/s eta 0:00:00
Collecting requests==2.28.2
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 4.7 MB/s eta 0:00:00
Collecting cryptography<39
  Using cached cryptography-38.0.4-cp36-abi3-macosx_10_10_universal2.whl (5.4 MB)
Collecting aioice-no-netifaces>=0.7.7post4
  Downloading aioice_no_netifaces-0.7.7.post4-py3-none-any.whl (23 kB)
Collecting google-crc32c>=1.1
  Downloading google_crc32c-1.5.0-cp311-cp311-macosx_10_9_universal2.whl (32 kB)
Collecting pyee>=9.0.0
  Using cached pyee-9.0.4-py2.py3-none-any.whl (14 kB)
Collecting pylibsrtp>=0.5.6
  Using cached pylibsrtp-0.8.0-cp311-cp311-macosx_11_0_arm64.whl (52 kB)
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.1.0-cp311-cp311-macosx_11_0_arm64.whl (121 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.7/121.7 kB 6.7 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 kB 4.4 MB/s eta 0:00:00
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests==2.28.2->-r requirements.txt (line 2)) (2022.12.7)
Collecting cffi>=1.12
  Using cached cffi-1.15.1-cp311-cp311-macosx_11_0_arm64.whl (174 kB)
Collecting dnspython>=2.0.0
  Using cached dnspython-2.3.0-py3-none-any.whl (283 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Installing collected packages: urllib3, typing-extensions, pycparser, idna, google-crc32c, dnspython, charset-normalizer, requests, pyee, cffi, aioice-no-netifaces, pylibsrtp, cryptography, aiortc-datachannel-only
Successfully installed aioice-no-netifaces-0.7.7.post4 aiortc-datachannel-only-1.3.2.post3 cffi-1.15.1 charset-normalizer-3.1.0 cryptography-38.0.4 dnspython-2.3.0 google-crc32c-1.5.0 idna-3.4 pycparser-2.21 pyee-9.0.4 pylibsrtp-0.8.0 requests-2.28.2 typing-extensions-4.5.0 urllib3-1.26.15
```

When I run the command ```python3 main.py --pin <5-char code>``` , I get this:

```
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiortc/rtcdtlstransport.py:211: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  _openssl_assert(lib.SSL_CTX_use_certificate(ctx, self._cert._x509) == 1)  # type: ignore
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiortc/rtcdtlstransport.py:186: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  value=certificate_digest(self._cert._x509),  # type: ignore
ERROR:root:[Errno 2] No such file or directory: 'wg'
```

New issue or continue here?

Any suggestions?

thanks :)

**Comment by alexanderhenne** [comment]
Have you installed wireguard?

**Comment by brad-taylor-yvr** [comment]
It's a fair question! Initially I did not :/, but I have installed it since and repeated the procedure, with the same outcome.

I see the wireguard icon in the menu bar.
Right-click the wg icon shows **Status:inactive**
About: 
- version: 1.0.16 (27)
- Go backend version: 1e2c3e5a

Do you know where this ```wg``` file/directory is supposed to be?

Here's the verbose output:

```
python3 main.py --pin <redacted> --verbose

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): client.amplifi.com:443
DEBUG:urllib3.connectionpool:https://client.amplifi.com:443 "POST /api/deviceToken/mlRequestClientAccess HTTP/1.1" 200 75
DEBUG:root:Raw client access response: {"client_id":"<redacted>","success":true}
DEBUG:asyncio:Using selector: KqueueSelector
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiortc/rtcdtlstransport.py:211: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  _openssl_assert(lib.SSL_CTX_use_certificate(ctx, self._cert._x509) == 1)  # type: ignore
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiortc/rtcdtlstransport.py:186: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
  value=certificate_digest(self._cert._x509),  # type: ignore
DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() setLocalDescription(offer)
v=0
o=- 3889131425 3889131425 IN IP4 0.0.0.0
s=-
t=0 0
a=group:BUNDLE 0
a=msid-semantic:WMS *
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=mid:0
a=sctpmap:5000 webrtc-datachannel 65535
a=max-message-size:65536
a=ice-ufrag:Z8D2
a=ice-pwd:a23QR4ZGrPDRkAlIUXrEau
a=fingerprint:sha-256 <redacted>
a=setup:actpass

DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() iceGatheringState new -> gathering
DEBUG:aioice.ice:aioice-no-netifaces does not support ipv6 yet
DEBUG:aioice.ice:Connection(0) protocol(0) connection_made(<_SelectorDatagramTransport fd=9 read=idle write=<idle, bufsize=0>>)
DEBUG:aioice.ice:Connection(0) protocol(0) > ('<redacted ipv4>', 3478) Message(message_method=1, message_class=0, transaction_id=b'd\xbaO\xb1\xea\xa3\xd6\x1evz&O')
DEBUG:aioice.ice:Connection(0) protocol(0) < ('<redacted ipv4>', 3478) Message(message_method=1, message_class=256, transaction_id=b'd\xbaO\xb1\xea\xa3\xd6\x1evz&O')
DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() iceGatheringState gathering -> complete
DEBUG:aiortc.rtcicetransport:RTCIceTransport(controlling) - new -> closed
DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() iceConnectionState new -> closed
DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() connectionState new -> closed
DEBUG:aioice.ice:Connection(0) protocol(0) connection_lost(None)
ERROR:root:[Errno 2] No such file or directory: 'wg'
```

I don't know python at all, so I appreciate your help. 

Is the root cause the missing wg file/folder, or the out of date pyOpenSSL (```This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.```) or something else?

**Comment by NassimBouhani** [comment]
> It's a fair question! Initially I did not :/, but I have installed it since and repeated the procedure, with the same outcome.
> 
> I see the wireguard icon in the menu bar. Right-click the wg icon shows **Status:inactive** About:
> 
> * version: 1.0.16 (27)
> * Go backend version: 1e2c3e5a
> 
> Do you know where this `wg` file/directory is supposed to be?
> 
> Here's the verbose output:
> 
> ```
> python3 main.py --pin <redacted> --verbose
> 
> DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): client.amplifi.com:443
> DEBUG:urllib3.connectionpool:https://client.amplifi.com:443 "POST /api/deviceToken/mlRequestClientAccess HTTP/1.1" 200 75
> DEBUG:root:Raw client access response: {"client_id":"<redacted>","success":true}
> DEBUG:asyncio:Using selector: KqueueSelector
> /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiortc/rtcdtlstransport.py:211: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
>   _openssl_assert(lib.SSL_CTX_use_certificate(ctx, self._cert._x509) == 1)  # type: ignore
> /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/aiortc/rtcdtlstransport.py:186: CryptographyDeprecationWarning: This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.
>   value=certificate_digest(self._cert._x509),  # type: ignore
> DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() setLocalDescription(offer)
> v=0
> o=- 3889131425 3889131425 IN IP4 0.0.0.0
> s=-
> t=0 0
> a=group:BUNDLE 0
> a=msid-semantic:WMS *
> m=application 9 DTLS/SCTP 5000
> c=IN IP4 0.0.0.0
> a=mid:0
> a=sctpmap:5000 webrtc-datachannel 65535
> a=max-message-size:65536
> a=ice-ufrag:Z8D2
> a=ice-pwd:a23QR4ZGrPDRkAlIUXrEau
> a=fingerprint:sha-256 <redacted>
> a=setup:actpass
> 
> DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() iceGatheringState new -> gathering
> DEBUG:aioice.ice:aioice-no-netifaces does not support ipv6 yet
> DEBUG:aioice.ice:Connection(0) protocol(0) connection_made(<_SelectorDatagramTransport fd=9 read=idle write=<idle, bufsize=0>>)
> DEBUG:aioice.ice:Connection(0) protocol(0) > ('<redacted ipv4>', 3478) Message(message_method=1, message_class=0, transaction_id=b'd\xbaO\xb1\xea\xa3\xd6\x1evz&O')
> DEBUG:aioice.ice:Connection(0) protocol(0) < ('<redacted ipv4>', 3478) Message(message_method=1, message_class=256, transaction_id=b'd\xbaO\xb1\xea\xa3\xd6\x1evz&O')
> DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() iceGatheringState gathering -> complete
> DEBUG:aiortc.rtcicetransport:RTCIceTransport(controlling) - new -> closed
> DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() iceConnectionState new -> closed
> DEBUG:aiortc.rtcpeerconnection:RTCPeerConnection() connectionState new -> closed
> DEBUG:aioice.ice:Connection(0) protocol(0) connection_lost(None)
> ERROR:root:[Errno 2] No such file or directory: 'wg'
> ```
> 
> I don't know python at all, so I appreciate your help.
> 
> Is the root cause the missing wg file/folder, or the out of date pyOpenSSL (`This version of cryptography contains a temporary pyOpenSSL fallback path. Upgrade pyOpenSSL now.`) or something else?

The wg.exe is a wireguard executable you need to install wireguard client, the file it self is in the instalation folder where wireguard resides.

in my case it generates the config like so but i'am unable to get any data or response, wireguard says it's connected but no traffic is getting sent, sent data 0 bytes , any solution for this , did something broke up after some amplifi updates ?:

this is the generted config :
[Interface]
PrivateKey = kIJ2pf6+QsE2LdNWXEHueSRGPtHl4IQir8VzHLPFlEQ=
ListenPort = 63415
Address = 192.168.196.151/32
DNS = 192.168.196.1

[Peer]
PublicKey = GPsdvrZ8PL8shq6gla++zas9ejP64K3SX1MbGXf6qXY=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 18.156.18.137:57900


And this is the wireguard state, saying handshake did not complete :

2023-05-14 21:30:19.257136: [TUN] [TELEPORT] Starting WireGuard/0.5.3 (Windows 10.0.22621; amd64)
2023-05-14 21:30:19.257136: [TUN] [TELEPORT] Watching network interfaces
2023-05-14 21:30:19.258721: [TUN] [TELEPORT] Resolving DNS names
2023-05-14 21:30:19.259137: [TUN] [TELEPORT] Creating network adapter
2023-05-14 21:30:19.387755: [TUN] [TELEPORT] Using existing driver 0.10
2023-05-14 21:30:19.388965: [TUN] [TELEPORT] Creating adapter
2023-05-14 21:30:19.632515: [TUN] [TELEPORT] Using WireGuardNT/0.10
2023-05-14 21:30:19.632515: [TUN] [TELEPORT] Enabling firewall rules
2023-05-14 21:30:19.582189: [TUN] [TELEPORT] Interface created
2023-05-14 21:30:19.641951: [TUN] [TELEPORT] Dropping privileges
2023-05-14 21:30:19.641951: [TUN] [TELEPORT] Setting interface configuration
2023-05-14 21:30:19.642484: [TUN] [TELEPORT] Peer 1 created
2023-05-14 21:30:19.647140: [TUN] [TELEPORT] Monitoring MTU of default v6 routes
2023-05-14 21:30:19.647140: [TUN] [TELEPORT] Interface up
2023-05-14 21:30:19.656357: [TUN] [TELEPORT] Setting device v6 addresses
2023-05-14 21:30:19.653677: [TUN] [TELEPORT] Sending handshake initiation to peer 1 (18.156.18.137:22188)
2023-05-14 21:30:19.689078: [TUN] [TELEPORT] Monitoring MTU of default v4 routes
2023-05-14 21:30:19.689078: [TUN] [TELEPORT] Setting device v4 addresses
2023-05-14 21:30:19.705538: [TUN] [TELEPORT] Startup complete
2023-05-14 21:30:24.703380: [TUN] [TELEPORT] Sending handshake initiation to peer 1 (18.156.18.137:22188)
2023-05-14 21:30:29.888324: [TUN] [TELEPORT] Handshake for peer 1 (18.156.18.137:22188) did not complete after 5 seconds, retrying (try 2)
2023-05-14 21:30:29.888324: [TUN] [TELEPORT] Sending handshake initiation to peer 1 (18.156.18.137:22188)
2023-05-14 21:30:34.988809: [TUN] [TELEPORT] Sending handshake initiation to peer 1 (18.156.18.137:22188)
2023-05-14 21:30:40.020522: [TUN] [TELEPORT] Handshake for peer 1 (18.156.18.137:22188) did not complete after 5 seconds, retrying (try 2)
2023-05-14 21:30:40.020522: [TUN] [TELEPORT] Sending handshake initiation to peer 1 (18.156.18.137:22188)
2023-05-14 21:30:45.038092: [TUN] [TELEPORT] Handshake for peer 1 (18.156.18.137:22188) did not complete after 5 seconds, retrying (try 2)
2023-05-14 21:30:45.038092: [TUN] [TELEPORT] Sending handshake initiation to peer 1 (18.156.18.137:22188)
2023-05-14 21:30:50.191359: [TUN] [TELEPORT] Handshake for peer 1 (18.156.18.137:22188) did not complete after 5 seconds, retrying (try 2)
2023-05-14 21:30:50.191359: [TUN] [TELEPORT] Sending handshake initiation to peer 1 (18.156.18.137:22188)
2023-05-14 21:30:55.221185: [TUN] [TELEPORT] Handshake for peer 1 (18.156.18.137:22188) did not complete after 5 seconds, retrying (try 2)
2023-05-14 21:30:55.221185: [TUN] [TELEPORT] Sending handshake initiation to peer 1 (18.156.18.137:22188)
2023-05-14 21:31:00.238721: [TUN] [TELEPORT] Handshake for peer 1 (18.156.18.137:22188) did not complete after 5 seconds, retrying (try 2)
2023-05-14 21:31:00.238721: [TUN] [TELEPORT] Sending handshake initiation to peer 1 (18.156.18.137:22188)
2023-05-14 21:31:05.276427: [TUN] [TELEPORT] Handshake for peer 1 (18.156.18.137:22188) did not complete after 5 seconds, retrying (try 2)
2023-05-14 21:31:05.276427: [TUN] [TELEPORT] Sending handshake initiation to peer 1 (18.156.18.137:22188)

**Comment by alexanderhenne** [comment]
@NassimBouhani You could try downgrading the router's firmware

Firmware: http://riga.corp.ubnt.com/file/stable/AFi-R.qca956x.v3.3.0.0-g3035af3f69.bin

Downgrade at: http://amplifi.lan/fwupdate.php
